# Example runtime defaults (optional). Leave empty to configure via .env or UI.
model:
  provider: ""
  name: ""
  temperature: 0.7
logging:
  level: INFO
tools:
  - name: echo
    description: Simple echo tool 